In [2]:
from math import floor
#import pywavefront as pw
from pprint import pprint
import numpy as np 
from matplotlib import pyplot as plt
from PIL import Image

In [3]:
def parser():
    lines = 0
    vts = []
    fs = []
    with open("./CUBE_TST.obj", "r") as f:
        lines = f.readlines()
    for line in lines:
        line = line.strip()
        if line[0:2]=="vt": #texture coordinate
            res = line.split(" ")
            vts.append([float(n) for n in res[1:]])

        if line[0] == "f":
            spl = line.split(" ")[1:]

            #extract texutre coordinates
            tis = [index-1 for index in [float(group.split("/")[1]) for group in spl]]
            face = [vts[int(i)] for i in tis]
            fs.append(face)
    #print(fs)
    return fs
parser()

[[[0.875, 0.5], [0.625, 0.75], [0.625, 0.5]],
 [[0.625, 0.75], [0.375, 1.0], [0.375, 0.75]],
 [[0.625, 0.0], [0.375, 0.25], [0.375, 0.0]],
 [[0.375, 0.5], [0.125, 0.75], [0.125, 0.5]],
 [[0.625, 0.5], [0.375, 0.75], [0.375, 0.5]],
 [[0.625, 0.25], [0.375, 0.5], [0.375, 0.25]],
 [[0.875, 0.5], [0.875, 0.75], [0.625, 0.75]],
 [[0.625, 0.75], [0.625, 1.0], [0.375, 1.0]],
 [[0.625, 0.0], [0.625, 0.25], [0.375, 0.25]],
 [[0.375, 0.5], [0.375, 0.75], [0.125, 0.75]],
 [[0.625, 0.5], [0.625, 0.75], [0.375, 0.75]],
 [[0.625, 0.25], [0.625, 0.5], [0.375, 0.5]],
 [[0.625, 0.0], [0.375, 0.25], [0.375, 0.0]],
 [[0.625, 0.25], [0.375, 0.5], [0.375, 0.25]],
 [[0.625, 0.5], [0.375, 0.75], [0.375, 0.5]],
 [[0.625, 0.75], [0.375, 1.0], [0.375, 0.75]],
 [[0.375, 0.5], [0.125, 0.75], [0.125, 0.5]],
 [[0.875, 0.5], [0.625, 0.75], [0.625, 0.5]],
 [[0.625, 0.0], [0.625, 0.25], [0.375, 0.25]],
 [[0.625, 0.25], [0.625, 0.5], [0.375, 0.5]],
 [[0.625, 0.5], [0.625, 0.75], [0.375, 0.75]],
 [[0.625, 0.75], [0.625,

In [26]:
def parseOutputs():
    with open("./output/output_0.txt", "r")  as f:
        lines = f.readlines()
        for line in lines:
            data = line.strip().split("\t")
            name = data[0]
            data = [float(n) for n in data[1:]]
            i, hu, hv, au, av, bu, bv, cu, cv = data
            face = np.asarray([[au, av], [bu, bv], [cu,cv]])
            point = [hu, hv, 1-hu-hv]
            coordinate = sum([pt*face for pt, face in zip(point, face)])
            print(face)
           # print(np.dot(face, point))

            #print(name, data)
parseOutputs()

[[ 0.  0.]
 [20.  0.]
 [ 0. 50.]]
[[-0.2      90.507788]
 [-0.       82.279808]
 [-0.       90.507788]]
[[-54.385695   8.197325]
 [ 54.385695   8.197325]
 [-52.556504  16.211535]]
[[ 0. 50.]
 [20.  0.]
 [20. 50.]]
[[-27.5       47.631397]
 [ 34.291939  43.000732]
 [ 27.5       47.631397]]
[[ 0.  0.]
 [20.  0.]
 [ 0. 50.]]
[[-54.385695   8.197325]
 [ 54.385695   8.197325]
 [-52.556504  16.211535]]
[[ 0. 50.]
 [20.  0.]
 [20. 50.]]
[[-54.385695   8.197325]
 [ 54.385695   8.197325]
 [-52.556504  16.211535]]
[[ 0. 50.]
 [20.  0.]
 [20. 50.]]
[[ 50.       -82.545123]
 [  0.2      -82.545123]
 [  0.2      -90.555737]]
[[ 0. 50.]
 [20.  0.]
 [20. 50.]]
[[ 0. 50.]
 [20.  0.]
 [20. 50.]]
[[-50.        77.05203 ]
 [ -0.2       85.433867]
 [-50.        85.433867]]
[[ 0. 50.]
 [20.  0.]
 [20. 50.]]
[[ 0.  0.]
 [20.  0.]
 [ 0. 50.]]
[[-54.385695   8.197325]
 [ 55.         0.      ]
 [ 54.385695   8.197325]]
[[ 0. 50.]
 [20.  0.]
 [20. 50.]]
[[-54.385695   8.197325]
 [ 55.         0.      ]
 [ 54.38